from typing import Literal

BOND_STATUS_BONDED = 'bonded'
BOND_STATUS_UNBONDED = 'unbonded'
BOND_STATUS_UNBONDING = 'unbonding'
BOND_STATUS_INVALID = 'invalid'
BondStatus = Literal[
    BOND_STATUS_BONDED, BOND_STATUS_UNBONDING, BOND_STATUS_UNBONDED,
    BOND_STATUS_INVALID
]

PROPOSAL_STATUS_UNSPECIFIED = 'unspecified'
PROPOSAL_STATUS_DEPOSIT_PERIOD = 'deposit_period'
PROPOSAL_STATUS_VOTING_PERIOD = 'voting_period'
PROPOSAL_STATUS_PASSED = 'passed'
PROPOSAL_STATUS_REJECTED = 'rejected'
PROPOSAL_STATUS_FAILED = 'failed'
PROPOSAL_STATUS_INVALID = 'invalid'
ProposalStatus = Literal[
    PROPOSAL_STATUS_UNSPECIFIED, PROPOSAL_STATUS_DEPOSIT_PERIOD,
    PROPOSAL_STATUS_VOTING_PERIOD, PROPOSAL_STATUS_PASSED,
    PROPOSAL_STATUS_REJECTED, PROPOSAL_STATUS_FAILED, PROPOSAL_STATUS_INVALID
]
