/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PanicDashboardOverview {
    }
    interface PanicFooter {
        "buttonsPosition": 'start' | 'end';
        "color": string;
        "githubURL": string;
        "headline": string;
        "headlinePosition": 'start' | 'end';
        "mediumURL": string;
        "telegramURL": string;
        "twitterURL": string;
        "websiteURL": string;
    }
    interface PanicHeader {
    }
    interface PanicRoot {
    }
}
declare global {
    interface HTMLPanicDashboardOverviewElement extends Components.PanicDashboardOverview, HTMLStencilElement {
    }
    var HTMLPanicDashboardOverviewElement: {
        prototype: HTMLPanicDashboardOverviewElement;
        new (): HTMLPanicDashboardOverviewElement;
    };
    interface HTMLPanicFooterElement extends Components.PanicFooter, HTMLStencilElement {
    }
    var HTMLPanicFooterElement: {
        prototype: HTMLPanicFooterElement;
        new (): HTMLPanicFooterElement;
    };
    interface HTMLPanicHeaderElement extends Components.PanicHeader, HTMLStencilElement {
    }
    var HTMLPanicHeaderElement: {
        prototype: HTMLPanicHeaderElement;
        new (): HTMLPanicHeaderElement;
    };
    interface HTMLPanicRootElement extends Components.PanicRoot, HTMLStencilElement {
    }
    var HTMLPanicRootElement: {
        prototype: HTMLPanicRootElement;
        new (): HTMLPanicRootElement;
    };
    interface HTMLElementTagNameMap {
        "panic-dashboard-overview": HTMLPanicDashboardOverviewElement;
        "panic-footer": HTMLPanicFooterElement;
        "panic-header": HTMLPanicHeaderElement;
        "panic-root": HTMLPanicRootElement;
    }
}
declare namespace LocalJSX {
    interface PanicDashboardOverview {
    }
    interface PanicFooter {
        "buttonsPosition"?: 'start' | 'end';
        "color"?: string;
        "githubURL"?: string;
        "headline"?: string;
        "headlinePosition"?: 'start' | 'end';
        "mediumURL"?: string;
        "telegramURL"?: string;
        "twitterURL"?: string;
        "websiteURL"?: string;
    }
    interface PanicHeader {
    }
    interface PanicRoot {
    }
    interface IntrinsicElements {
        "panic-dashboard-overview": PanicDashboardOverview;
        "panic-footer": PanicFooter;
        "panic-header": PanicHeader;
        "panic-root": PanicRoot;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "panic-dashboard-overview": LocalJSX.PanicDashboardOverview & JSXBase.HTMLAttributes<HTMLPanicDashboardOverviewElement>;
            "panic-footer": LocalJSX.PanicFooter & JSXBase.HTMLAttributes<HTMLPanicFooterElement>;
            "panic-header": LocalJSX.PanicHeader & JSXBase.HTMLAttributes<HTMLPanicHeaderElement>;
            "panic-root": LocalJSX.PanicRoot & JSXBase.HTMLAttributes<HTMLPanicRootElement>;
        }
    }
}
