/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PanicAlertsOverview {
    }
    interface PanicDashboardOverview {
    }
    interface PanicFooter {
    }
    interface PanicHeader {
    }
    interface PanicRoot {
    }
    interface PanicSystemsOverview {
        /**
          * The name of the selected base chain.
         */
        "baseChainName": string;
    }
}
declare global {
    interface HTMLPanicAlertsOverviewElement extends Components.PanicAlertsOverview, HTMLStencilElement {
    }
    var HTMLPanicAlertsOverviewElement: {
        prototype: HTMLPanicAlertsOverviewElement;
        new (): HTMLPanicAlertsOverviewElement;
    };
    interface HTMLPanicDashboardOverviewElement extends Components.PanicDashboardOverview, HTMLStencilElement {
    }
    var HTMLPanicDashboardOverviewElement: {
        prototype: HTMLPanicDashboardOverviewElement;
        new (): HTMLPanicDashboardOverviewElement;
    };
    interface HTMLPanicFooterElement extends Components.PanicFooter, HTMLStencilElement {
    }
    var HTMLPanicFooterElement: {
        prototype: HTMLPanicFooterElement;
        new (): HTMLPanicFooterElement;
    };
    interface HTMLPanicHeaderElement extends Components.PanicHeader, HTMLStencilElement {
    }
    var HTMLPanicHeaderElement: {
        prototype: HTMLPanicHeaderElement;
        new (): HTMLPanicHeaderElement;
    };
    interface HTMLPanicRootElement extends Components.PanicRoot, HTMLStencilElement {
    }
    var HTMLPanicRootElement: {
        prototype: HTMLPanicRootElement;
        new (): HTMLPanicRootElement;
    };
    interface HTMLPanicSystemsOverviewElement extends Components.PanicSystemsOverview, HTMLStencilElement {
    }
    var HTMLPanicSystemsOverviewElement: {
        prototype: HTMLPanicSystemsOverviewElement;
        new (): HTMLPanicSystemsOverviewElement;
    };
    interface HTMLElementTagNameMap {
        "panic-alerts-overview": HTMLPanicAlertsOverviewElement;
        "panic-dashboard-overview": HTMLPanicDashboardOverviewElement;
        "panic-footer": HTMLPanicFooterElement;
        "panic-header": HTMLPanicHeaderElement;
        "panic-root": HTMLPanicRootElement;
        "panic-systems-overview": HTMLPanicSystemsOverviewElement;
    }
}
declare namespace LocalJSX {
    interface PanicAlertsOverview {
    }
    interface PanicDashboardOverview {
    }
    interface PanicFooter {
    }
    interface PanicHeader {
    }
    interface PanicRoot {
    }
    interface PanicSystemsOverview {
        /**
          * The name of the selected base chain.
         */
        "baseChainName"?: string;
    }
    interface IntrinsicElements {
        "panic-alerts-overview": PanicAlertsOverview;
        "panic-dashboard-overview": PanicDashboardOverview;
        "panic-footer": PanicFooter;
        "panic-header": PanicHeader;
        "panic-root": PanicRoot;
        "panic-systems-overview": PanicSystemsOverview;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "panic-alerts-overview": LocalJSX.PanicAlertsOverview & JSXBase.HTMLAttributes<HTMLPanicAlertsOverviewElement>;
            "panic-dashboard-overview": LocalJSX.PanicDashboardOverview & JSXBase.HTMLAttributes<HTMLPanicDashboardOverviewElement>;
            "panic-footer": LocalJSX.PanicFooter & JSXBase.HTMLAttributes<HTMLPanicFooterElement>;
            "panic-header": LocalJSX.PanicHeader & JSXBase.HTMLAttributes<HTMLPanicHeaderElement>;
            "panic-root": LocalJSX.PanicRoot & JSXBase.HTMLAttributes<HTMLPanicRootElement>;
            "panic-systems-overview": LocalJSX.PanicSystemsOverview & JSXBase.HTMLAttributes<HTMLPanicSystemsOverviewElement>;
        }
    }
}
