from ..alert_code import AlertCode


class SubstrateNodeAlertCode(AlertCode):
    NodeWentDownAtAlert = 'substrate_node_alert_1'
    NodeBackUpAgainAlert = 'substrate_node_alert_2'
    NodeStillDownAlert = 'substrate_node_alert_3'
    NoChangeInBestBlockHeightAlert = 'substrate_node_alert_4'
    BestBlockHeightUpdatedAlert = 'substrate_node_alert_5'
    NoChangeInFinalizedBlockHeightAlert = 'substrate_node_alert_6'
    FinalizedBlockHeightUpdatedAlert = 'substrate_node_alert_7'
    NodeIsSyncingAlert = 'substrate_node_alert_8'
    NodeIsNoLongerSyncingAlert = 'substrate_node_alert_9'
    ValidatorIsNotActiveAlert = 'substrate_node_alert_10'
    ValidatorIsActiveAlert = 'substrate_node_alert_11'
    ValidatorIsDisabledAlert = 'substrate_node_alert_12'
    ValidatorIsNoLongerDisabledAlert = 'substrate_node_alert_13'
    ValidatorWasNotElectedAlert = 'substrate_node_alert_14'
    ValidatorWasElectedAlert = 'substrate_node_alert_15'
    ValidatorBondedAmountChangedAlert = 'substrate_node_alert_16'
    ValidatorNoHeartbeatAndBlockAuthoredYetAlert = 'substrate_node_alert_17'
    ValidatorHeartbeatSentOrBlockAuthoredAlert = 'substrate_node_alert_18'
    ValidatorWasOfflineAlert = 'substrate_node_alert_19'
    ValidatorWasSlashedAlert = 'substrate_node_alert_20'
    ValidatorPayoutNotClaimedAlert = 'substrate_node_alert_21'
    ValidatorPayoutClaimedAlert = 'substrate_node_alert_22'
    ValidatorControllerAddressChangedAlert = 'substrate_node_alert_23'
    ErrorNoSyncedSubstrateWebSocketDataSourcesAlert = 'substrate_node_alert_24'
    SyncedSubstrateWebSocketDataSourcesFoundAlert = 'substrate_node_alert_25'
    SubstrateWebSocketDataCouldNotBeObtainedAlert = 'substrate_node_alert_26'
    SubstrateWebSocketDataObtainedAlert = 'substrate_node_alert_27'
    SubstrateApiIsNotReachableAlert = 'substrate_node_alert_28'
    SubstrateApiIsReachableAlert = 'substrate_node_alert_29'
