// Channel related actions
export const ADD_TELEGRAM = 'ADD_TELEGRAM';
export const REMOVE_TELEGRAM = 'REMOVE_TELEGRAM';
export const ADD_TWILIO = 'ADD_TWILIO';
export const REMOVE_TWILIO = 'REMOVE_TWILIO';
export const ADD_EMAIL = 'ADD_EMAIL';
export const REMOVE_EMAIL = 'REMOVE_EMAIL';
export const ADD_PAGERDUTY = 'ADD_PAGERDUTY';
export const REMOVE_PAGERDUTY = 'REMOVE_PAGERDUTY';
export const ADD_OPSGENIE = 'ADD_OPSGENIE';
export const REMOVE_OPSGENIE = 'REMOVE_OPSGENIE';

// Page related actions
export const CHANGE_PAGE = 'CHANGE_PAGE';
export const CHANGE_STEP = 'CHANGE_STEP';

// Comsos chains related actions
export const ADD_CHAIN_COSMOS = 'ADD_CHAIN_COSMOS';
export const ADD_NODE_COSMOS = 'ADD_NODE_COSMOS';
export const REMOVE_NODE_COSMOS = 'REMOVE_NODE_COSMOS';
export const ADD_REPOSITORY_COSMOS = 'ADD_REPOSITORY_COSMOS';
export const REMOVE_REPOSITORY_COSMOS = 'REMOVE_REPOSITORY_COSMOS';
export const ADD_KMS_COSMOS = 'ADD_KMS_COSMOS';
export const REMOVE_KMS_COSMOS = 'REMOVE_KMS_COSMOS';
export const ADD_CHANNEL_COSMOS = 'ADD_CHANNEL_COSMOS';
export const REMOVE_CHANNEL_COSMOS = 'REMOVE_CHANNEL_COSMOS';
export const SET_ALERTS_COSMOS = 'SET_ALERTS_COSMOS';
export const ADD_CONFIG_COSMOS = 'ADD_CONFIG_COSMOS';
export const REMOVE_CONFIG_COSMOS = 'REMOVE_CONFIG_COSMOS';
export const RESET_CONFIG_COSMOS = 'RESET_CONFIG_COSMOS';
export const LOAD_CONFIG_COSMOS = 'LOAD_CONFIG_COSMOS';
export const ADD_TELEGRAM_CHANNEL_COSMOS = 'ADD_TELEGRAM_CHANNEL_COSMOS';
export const REMOVE_TELEGRAM_CHANNEL_COSMOS = 'REMOVE_TELEGRAM_CHANNEL_COSMOS';
export const ADD_OPSGENIE_CHANNEL_COSMOS = 'ADD_OPSGENIE_CHANNEL_COSMOS';
export const REMOVE_OPSGENIE_CHANNEL_COSMOS = 'REMOVE_OPSGENIE_CHANNEL_COSMOS';
export const ADD_EMAIL_CHANNEL_COSMOS = 'ADD_EMAIL_CHANNEL_COSMOS';
export const REMOVE_EMAIL_CHANNEL_COSMOS = 'REMOVE_EMAIL_CHANNEL_COSMOS';
export const ADD_PAGERDUTY_CHANNEL_COSMOS = 'ADD_PAGERDUTY_CHANNEL_COSMOS';
export const REMOVE_PAGERDUTY_CHANNEL_COSMOS = 'REMOVE_PAGERDUTY_CHANNEL_COSMOS';
export const ADD_TWILIO_CHANNEL_COSMOS = 'ADD_TWILIO_CHANNEL_COSMOS';
export const REMOVE_TWILIO_CHANNEL_COSMOS = 'REMOVE_TWILIO_CHANNEL_COSMOS';

// Cosmos alerts with thresholds related actions
export const UPDATE_WARNING_DELAY_COSMOS = 'UPDATE_WARNING_DELAY_COSMOS';
export const UPDATE_WARNING_REPEAT_COSMOS = 'UPDATE_WARNING_REPEAT_COSMOS';
export const UPDATE_WARNING_THRESHOLD_COSMOS = 'UPDATE_WARNING_THRESHOLD_COSMOS';
export const UPDATE_WARNING_TIMEWINDOW_COSMOS = 'UPDATE_WARNING_TIMEWINDOW_COSMOS';
export const UPDATE_WARNING_ENABLED_COSMOS = 'UPDATE_WARNING_ENABLED_COSMOS';
export const UPDATE_CRITICAL_DELAY_COSMOS = 'UPDATE_CRITICAL_DELAY_COSMOS';
export const UPDATE_CRITICAL_REPEAT_COSMOS = 'UPDATE_CRITICAL_REPEAT_COSMOS';
export const UPDATE_CRITICAL_THRESHOLD_COSMOS = 'UPDATE_CRITICAL_THRESHOLD_COSMOS';
export const UPDATE_CRITICAL_TIMEWINDOW_COSMOS = 'UPDATE_CRITICAL_TIMEWINDOW_COSMOS';
export const UPDATE_CRITICAL_ENABLED_COSMOS = 'UPDATE_CRITICAL_ENABLED_COSMOS';
export const UPDATE_ALERT_ENABLED_COSMOS = 'UPDATE_ALERT_ENABLED_COSMOS';

// Cosmos alerts with severties related actions
export const UPDATE_ALERT_SEVERTY_LEVEL_COSMOS = 'UPDATE_ALERT_SEVERTY_LEVEL_COSMOS';
export const UPDATE_ALERT_SEVERTY_ENABLED_COSMOS = 'UPDATE_ALERT_SEVERTY_ENABLED_COSMOS';

// Substrate chains related actions
export const ADD_CHAIN_SUBSTRATE = 'ADD_CHAIN_SUBSTRATE';
export const ADD_NODE_SUBSTRATE = 'ADD_NODE_SUBSTRATE';
export const REMOVE_NODE_SUBSTRATE = 'REMOVE_NODE_SUBSTRATE';
export const ADD_REPOSITORY_SUBSTRATE = 'ADD_REPOSITORY_SUBSTRATE';
export const REMOVE_REPOSITORY_SUBSTRATE = 'REMOVE_REPOSITORY_SUBSTRATE';
export const ADD_KMS_SUBSTRATE = 'ADD_KMS_SUBSTRATE';
export const REMOVE_KMS_SUBSTRATE = 'REMOVE_KMS_SUBSTRATE';
export const ADD_CHANNEL_SUBSTRATE = 'ADD_CHANNEL_SUBSTRATE';
export const REMOVE_CHANNEL_SUBSTRATE = 'REMOVE_CHANNEL_SUBSTRATE';
export const SET_ALERTS_SUBSTRATE = 'SET_ALERTS_SUBSTRATE';
export const ADD_CONFIG_SUBSTRATE = 'ADD_CONFIG_SUBSTRATE';
export const REMOVE_CONFIG_SUBSTRATE = 'REMOVE_CONFIG_SUBSTRATE';
export const RESET_CONFIG_SUBSTRATE = 'RESET_CONFIG_SUBSTRATE';
export const LOAD_CONFIG_SUBSTRATE = 'LOAD_CONFIG_SUBSTRATE';
export const ADD_TELEGRAM_CHANNEL_SUBSTRATE = 'ADD_TELEGRAM_CHANNEL_SUBSTRATE';
export const REMOVE_TELEGRAM_CHANNEL_SUBSTRATE = 'REMOVE_TELEGRAM_CHANNEL_SUBSTRATE';
export const ADD_OPSGENIE_CHANNEL_SUBSTRATE = 'ADD_OPSGENIE_CHANNEL_SUBSTRATE';
export const REMOVE_OPSGENIE_CHANNEL_SUBSTRATE = 'REMOVE_OPSGENIE_CHANNEL_SUBSTRATE';
export const ADD_EMAIL_CHANNEL_SUBSTRATE = 'ADD_EMAIL_CHANNEL_SUBSTRATE';
export const REMOVE_EMAIL_CHANNEL_SUBSTRATE = 'REMOVE_EMAIL_CHANNEL_SUBSTRATE';
export const ADD_PAGERDUTY_CHANNEL_SUBSTRATE = 'ADD_PAGERDUTY_CHANNEL_SUBSTRATE';
export const REMOVE_PAGERDUTY_CHANNEL_SUBSTRATE = 'REMOVE_PAGERDUTY_CHANNEL_SUBSTRATE';
export const ADD_TWILIO_CHANNEL_SUBSTRATE = 'ADD_TWILIO_CHANNEL_SUBSTRATE';
export const REMOVE_TWILIO_CHANNEL_SUBSTRATE = 'REMOVE_TWILIO_CHANNEL_SUBSTRATE';

// Alerts with thresholds related actions
export const UPDATE_WARNING_DELAY_SUBSTRATE = 'UPDATE_WARNING_DELAY_SUBSTRATE';
export const UPDATE_WARNING_REPEAT_SUBSTRATE = 'UPDATE_WARNING_REPEAT_SUBSTRATE';
export const UPDATE_WARNING_THRESHOLD_SUBSTRATE = 'UPDATE_WARNING_THRESHOLD_SUBSTRATE';
export const UPDATE_WARNING_TIMEWINDOW_SUBSTRATE = 'UPDATE_WARNING_TIMEWINDOW_SUBSTRATE';
export const UPDATE_WARNING_ENABLED_SUBSTRATE = 'UPDATE_WARNING_ENABLED_SUBSTRATE';
export const UPDATE_CRITICAL_DELAY_SUBSTRATE = 'UPDATE_CRITICAL_DELAY_SUBSTRATE';
export const UPDATE_CRITICAL_REPEAT_SUBSTRATE = 'UPDATE_CRITICAL_REPEAT_SUBSTRATE';
export const UPDATE_CRITICAL_THRESHOLD_SUBSTRATE = 'UPDATE_CRITICAL_THRESHOLD_SUBSTRATE';
export const UPDATE_CRITICAL_TIMEWINDOW_SUBSTRATE = 'UPDATE_CRITICAL_TIMEWINDOW_SUBSTRATE';
export const UPDATE_CRITICAL_ENABLED_SUBSTRATE = 'UPDATE_CRITICAL_ENABLED_SUBSTRATE';
export const UPDATE_ALERT_ENABLED_SUBSTRATE = 'UPDATE_ALERT_ENABLED_SUBSTRATE';

// Alerts with severties related actions
export const UPDATE_ALERT_SEVERTY_LEVEL_SUBSTRATE = 'UPDATE_ALERT_SEVERTY_LEVEL_SUBSTRATE';
export const UPDATE_ALERT_SEVERTY_ENABLED_SUBSTRATE = 'UPDATE_ALERT_SEVERTY_ENABLED_SUBSTRATE';

// General page
export const UPDATE_PERIODIC = 'UPDATE_PERIODIC';
export const ADD_REPOSITORY = 'ADD_REPOSITORY';
export const ADD_SYSTEM = 'ADD_SYSTEM';
export const REMOVE_REPOSITORY = 'REMOVE_REPOSITORY';
export const REMOVE_SYSTEM = 'REMOVE_SYSTEM';

// Users Page, containing only actions to set and remove users
export const ADD_USER = 'ADD_USER';
export const REMOVE_USER = 'REMOVE_USER';

// Login actions
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
