export const ADD_TELEGRAM = 'ADD_TELEGRAM';
export const REMOVE_TELEGRAM = 'REMOVE_TELEGRAM';
export const ADD_TWILIO = 'ADD_TWILIO';
export const REMOVE_TWILIO = 'REMOVE_TWILIO';
export const CHANGE_PAGE = 'CHANGE_PAGE';
